version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: reportportal-postgres
    environment:
      POSTGRES_USER: rpuser
      POSTGRES_PASSWORD: rppass
      POSTGRES_DB: reportportal
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: reportportal-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    restart: unless-stopped
    ports:
      - "9200:9200"

  reportportal:
    image: reportportal/service-api:5.11.0
    container_name: reportportal-api
    depends_on:
      - postgres
      - elasticsearch
    environment:
      RP_DB_HOST: postgres
      RP_DB_USER: rpuser
      RP_DB_PASS: rppass
      RP_DB_NAME: reportportal
      RP_ELASTICSEARCH_HOST: elasticsearch
      RP_ELASTICSEARCH_PORT: 9200
      JAVA_OPTS: "-Xmx1g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp"
    restart: unless-stopped
    ports:
      - "8080:8080"

  reportportal-ui:
    image: reportportal/service-ui:5.11.0
    container_name: reportportal-ui
    depends_on:
      - reportportal
    environment:
      RP_SERVER_PORT: 8080
    restart: unless-stopped
    ports:
      - "8090:8080"

volumes:
  postgres_data:
  elasticsearch_data: